### ISSUE TITLE
Compiled library not working under macOS M1 architecture

### ISSUE THREAD

**Issue by hagenw** [audeering/audresamplelib#1]
Compare error reported under https://github.com/audeering/audresample/issues/21

@chausner-audeering is it possible that we support that architecture with `audresamplelib`?

**Comment by chausner-audeering** [comment]
Yes, that should be possible by cross-compiling for M1. But we might want to first revise how we build the library. I see our internal clone of this project on GitLab has been archived recently but we have had used it in the past for getting builds from CI, I believe.

Anyway, going forward, the cleanest solution would probably be to leverage the GitHub CI to build this library. And even if there are no M1 runners supported by GitHub at the moment, it might still be possible to cross-compile for M1 but not sure.

**Comment by Linux13524** [comment]
@hagenw Can we close this issue?

**Comment by hagenw** [comment]
Yes, this was fixed in https://github.com/audeering/audresample/pull/33
