### ISSUE TITLE
Project cannot be build by community

### ISSUE THREAD

**Issue by hagenw** [audeering/audresamplelib#2]
Inside `conanfile.txt` we have the following two lines:

```
soxr/0.1.3@audeering/testing
dr_wav/0.12.12@audeering/testing
```

which means the project cannot be build by the community as it fails with

```
soxr/0.1.3@audeering/testing: Not found in local cache, looking in remotes...
soxr/0.1.3@audeering/testing: Trying with 'conancenter'...
ERROR: Unable to find 'soxr/0.1.3@audeering/testing' in remotes
```

compare https://github.com/audeering/audresample/issues/21

**Comment by Linux13524** [comment]
We should use soxr and dr_wav from Conan Center, see:
- https://conan.io/center/soxr
- https://conan.io/center/drwav
